# Generated by Django 2.1.7 on 2019-03-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleUs', '0002_auto_20190329_0522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together=set(),
        ),
    ]
